-- Run in Supabase Dashboard -> SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.pings (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
alter table public.pings enable row level security;
grant select on public.profiles to authenticated;
grant select, insert on public.pings to authenticated;
drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "Users can read their own pings" on public.pings;
create policy "Users can read their own pings" on public.pings for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can insert their own pings" on public.pings;
create policy "Users can insert their own pings" on public.pings for insert to authenticated with check ((select auth.uid()) = user_id);
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
