-- Run this script in Supabase Dashboard -> SQL Editor.
-- It creates the protected tables and policies used by the starter app.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.pings (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.credit_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists credit_cards_user_sort_idx on public.credit_cards (user_id, sort_order, created_at);

alter table public.profiles enable row level security;
alter table public.pings enable row level security;
alter table public.credit_cards enable row level security;

grant select on public.profiles to authenticated;
grant select, insert on public.pings to authenticated;
grant select, insert, update, delete on public.credit_cards to authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);

drop policy if exists "Users can read their own pings" on public.pings;
create policy "Users can read their own pings" on public.pings for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own pings" on public.pings;
create policy "Users can insert their own pings" on public.pings for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read their own credit cards" on public.credit_cards;
create policy "Users can read their own credit cards" on public.credit_cards for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can add their own credit cards" on public.credit_cards;
create policy "Users can add their own credit cards" on public.credit_cards for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own credit cards" on public.credit_cards;
create policy "Users can update their own credit cards" on public.credit_cards for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own credit cards" on public.credit_cards;
create policy "Users can delete their own credit cards" on public.credit_cards for delete to authenticated using ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

notify pgrst, 'reload schema';
